name: threat_modelling
channels:
  - defaults
  - conda
  - conda-forge
dependencies:
  - python-graphviz
  - python=3.7.10
  - pytest=6.2.5
  - pytest-cov=3.0.0
  - autopep8=1.6.0
  - flake8=4.0.1
  - isort=5.9.3
  - matplotlib=3.5.2
  - networkx=2.6.3
  - pylint=2.14.5
  - pyyaml=6.0.0
  - pip=21.2.4
  - pip:
      - safety==2.1.1
      - -e .